---
- id: ros2_ws_same_versions_lint
  name: Ensure all ROS2 packages are of the same version
  description: Ensures all packages in the workspace are of the same version
  entry: ros2_ws_same_versions_lint
  language: script
  pass_filenames: false
